services:
  db:
    image: postgres:16
    container_name: project_db
    restart: unless-stopped
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: tic
      POSTGRES_PASSWORD: tac
      POSTGRES_DB: tic-tac-toe
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tic -d tic-tac-toe"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
